language: node_js
node_js:
  - "11"
cache: yarn

services:
  - chrome: stable


  
script:
- yarn lint
- yarn test --watch=false --browsers=ChromeHeadless
- yarn build --prod
- yarn run e2e
- yarn serve